public class MyClass {
    public static void main(String args[]) {
      int x=10;
      int y=25;
      int z=x+y;
      
    //   String s1="Hello";
    //  String s2="World";
    //   String s4="";
    //   System.out.println(1000+z);
      // 1000 + z
    //   String s3 = s1+" "+s2;
    //   System.out.println(s1);
    //   System.out.println(s2);
    //   System.out.println(s3);
    // System.out.println(s4);
    //Rani is learning Java-- ye
    String s5="Rani";
    // String s6="is";
    // String s7="learning";
    String s8="java";
    // String s9= s5 + s6+ s7+ s8;
    System.out.println( s5+"_"+s8);
    }
}
//string literals ko print kar skte hai 
// variables ko v dal sakte hai sop
